/*
  +----------------------------------------------------------------------+
  | php-temporal — native async Temporal client for PHP TrueAsync        |
  +----------------------------------------------------------------------+
  | Licensed under the Apache License, Version 2.0 (the "License").       |
  +----------------------------------------------------------------------+

  Thin, Zend-free C wrapper over the Temporal Rust core c-bridge.

  Only temporal_core.c includes <temporal-sdk-core-c-bridge.h>. That header is
  generated by cbindgen with unprefixed enum constants (e.g. `Debug`, `Error`,
  `Workflow`) that clash with php.h symbols, so we keep it out of every
  translation unit that pulls in Zend. The glue layer talks to the core only
  through this header, passing opaque pointers and plain C types. This split also
  keeps the Tokio-thread callback path free of Zend/TSRM, by design.

  Wrappers are prefixed `tphp_` to avoid colliding with the bridge's own
  `temporal_core_*` symbols.
*/

#ifndef PHP_TEMPORAL_CORE_H
#define PHP_TEMPORAL_CORE_H

#include <stdbool.h>
#include <stddef.h>

/* --- Runtime (one Tokio runtime per process) --------------------------- */

/* Create the core runtime. Returns an opaque handle, or NULL with *err_out set
 * to a heap-allocated message the caller must free(). */
void *tphp_runtime_new(char **err_out);
void  tphp_runtime_free(void *runtime);

/* --- Client connect ---------------------------------------------------- */

typedef struct {
	const char *target_url;      /* full URL incl. scheme, e.g. "http://host:7233" */
	const char *client_name;
	const char *client_version;
	const char *identity;        /* or NULL */
	const char *api_key;         /* or NULL */
	bool        tls_enabled;
	const char *tls_server_root_ca_cert; /* PEM, or NULL */
	const char *tls_client_cert;
	const char *tls_client_private_key;
	const char *tls_server_name;
} tphp_connect_params_t;

/* Delivery callback, invoked on a core (Tokio) thread when connect finishes.
 * Exactly one of `connection` / `fail` is non-NULL. `fail` is a heap string;
 * ownership passes to the callback. The callback must be Zend/TSRM-free. */
typedef void (*tphp_connect_done_cb)(void *user_data, void *connection, char *fail);

/* Start an async connect. params and its strings are copied internally, so the
 * caller need not keep them alive past this call. */
void tphp_connect(void *runtime, const tphp_connect_params_t *params,
                  void *user_data, tphp_connect_done_cb done);

void tphp_connection_free(void *connection);

/* --- Async RPC --------------------------------------------------------- */

/* gRPC service selector (mirrors the core's TemporalCoreRpcService enum). */
enum {
	TPHP_SERVICE_WORKFLOW = 1,
	TPHP_SERVICE_OPERATOR = 2,
	TPHP_SERVICE_CLOUD    = 3,
	TPHP_SERVICE_TEST     = 4,
	TPHP_SERVICE_HEALTH   = 5,
};

/* Delivery callback, invoked on a core (Tokio) thread when the RPC finishes.
 * On success `success` (`success_len` bytes) points into the core-owned buffer
 * `success_owner` — NOT copied; the reactor reads it directly and then releases
 * it with tphp_response_free(). On failure `fail` (heap string, `fail_len` bytes)
 * and `status_code` carry the gRPC error. Must be Zend/TSRM-free. */
typedef void (*tphp_rpc_done_cb)(void *user_data,
                                 const uint8_t *success, size_t success_len, void *success_owner,
                                 uint32_t status_code,
                                 char *fail, size_t fail_len,
                                 uint8_t *details, size_t details_len);

/* Issue an async unary RPC. `method`, `req` and `metadata` are copied
 * internally. Each `metadata[i]` is a NUL-terminated "<key>\n<value>" string
 * (the core's metadata wire form); pass NULL/0 for none. `cancel_token` (or NULL)
 * lets the caller abort the in-flight RPC; the core clones it internally. */
void tphp_rpc_call(void *runtime, void *connection, int service,
                   const char *method, const uint8_t *req, size_t req_len,
                   uint32_t timeout_ms,
                   const char *const *metadata, size_t metadata_count,
                   void *cancel_token,
                   void *user_data, tphp_rpc_done_cb done);

/* Cancellation token for an in-flight RPC. Create on the reactor, hand to
 * tphp_rpc_call, call cancel() to abort the call promptly, then free(). The core
 * clones the token internally, so the wrapper is owned solely by the reactor
 * side — no cross-thread races. cancel() is idempotent. */
void *tphp_cancel_token_new(void);
void  tphp_cancel_token_cancel(void *token);
void  tphp_cancel_token_free(void *token);

/* Release a core-owned response buffer handed to tphp_rpc_done_cb as
 * `success_owner`. Safe to call from any thread; no-op on NULL. */
void tphp_response_free(void *response_owner);

/* --- Worker ------------------------------------------------------------ */

/* Worker tuning. Every field must be filled (the PHP layer applies defaults);
 * slot counts and poller maximums are fixed-size/simple-maximum strategies. */
typedef struct {
	uint32_t activity_slots;
	uint32_t workflow_slots;
	uint32_t local_activity_slots;
	uint32_t nexus_slots;
	uint32_t max_cached_workflows;
	uint64_t sticky_schedule_to_start_ms;
	uint64_t graceful_shutdown_ms;
	uint32_t activity_pollers;
	uint32_t workflow_pollers;
	uint32_t nexus_pollers;
} tphp_worker_options_t;

/* Create a worker on a task queue handling both workflow and activity tasks.
 * Returns an opaque handle, or NULL with *err_out (heap, caller frees).
 * worker_new is synchronous in the core. */
void *tphp_worker_new(void *connection, const char *ns, const char *task_queue,
                      const tphp_worker_options_t *options, char **err_out);
void  tphp_worker_free(void *worker);
void  tphp_worker_initiate_shutdown(void *worker);

/* Poll delivery (core thread). Exactly one case:
 *   - a task   : `task` (`task_len` bytes) borrows the core-owned `task_owner`
 *                (release with tphp_response_free); `fail` is NULL.
 *   - shutdown : task, task_owner AND fail are all NULL.
 *   - error    : `fail` (heap) is set.
 * Must be Zend/TSRM-free. */
typedef void (*tphp_worker_poll_cb)(void *user_data,
                                    const uint8_t *task, size_t task_len, void *task_owner,
                                    char *fail, size_t fail_len);
void tphp_worker_poll_activity(void *worker, void *user_data, tphp_worker_poll_cb done);
void tphp_worker_poll_workflow(void *worker, void *user_data, tphp_worker_poll_cb done);

/* Completion of a void worker op (complete activity/workflow, finalize shutdown).
 * `fail` (heap) is NULL on success. Must be Zend/TSRM-free. */
typedef void (*tphp_worker_done_cb)(void *user_data, char *fail, size_t fail_len);
void tphp_worker_complete_activity(void *worker, const uint8_t *completion, size_t len,
                                   void *user_data, tphp_worker_done_cb done);
void tphp_worker_complete_workflow(void *worker, const uint8_t *completion, size_t len,
                                   void *user_data, tphp_worker_done_cb done);
void tphp_worker_finalize_shutdown(void *worker, void *user_data, tphp_worker_done_cb done);

/* Record an activity heartbeat (serialized coresdk ActivityHeartbeat).
 * Synchronous in the core: it only stores the heartbeat in memory; throttling
 * and the server RPC happen later on the core's own threads. Returns NULL on
 * success, or a heap error message (decode failure) the caller frees. */
char *tphp_worker_record_heartbeat(void *worker, const uint8_t *heartbeat, size_t len);

#endif /* PHP_TEMPORAL_CORE_H */
